---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:v0.11.1
    container_name: nebula-sync
    environment:
    - PRIMARY=${PRIMARY}
    - REPLICAS=${REPLICAS}
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *