- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: group
          widgets:
            - type: hacker-news   
            - type: rss
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://selfh.st/rss/
                  title: selfh.st   
        

    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Misc
          sites:
            - title: Pocket-ID
              url: https://id.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pocket-id.svg
            - title: Outline
              url: https://docs.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/outline.svg
            - title: IT-Tools
              url: https://tools.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/it-tools.svg
        - type: monitor
          cache: 1m
          title: Monitoring
          sites:
            - title: Dozzle
              url: https://dozzle.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/dozzle.svg
            - title: Portainer
              url: https://portainer.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/portainer.svg
        - type: monitor
          cache: 1m
          title: Network
          sites:
            - title: Technitium-01
              url: https://dns-01.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/technitium.svg
        - type: monitor
          cache: 1m
          title: Appliances
          sites:
            - title: Unraid
              url: https://unraid.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/unraid.svg
            - title: PVE-01
              url: https://pve-s13-01.local.darksaber.fyi:8006/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/proxmox.svg
            - title: PVE-02
              url: https://pve-s13-01.local.darksaber.fyi:8006/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/proxmox.svg
            - title: Unifi
              url: https://unifi.ui.com/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/ubiquiti-unifi-light.svg

    - size: small
      widgets:
        - type: weather
          units: metric
          hour-format: 24h
          location: Hannover, Germany
        - type: server-stats
          servers:
            - type: local
              name: srv-docker
        - type: repository
          repository: L3odalton/homelab-2.0

