- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Misc
          sites:
            - title: Pocket-ID
              url: https://id.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pocket-id.svg
            - title: Outline
              url: https://outline.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/outline.svg
            - title: IT-Tools
              url: https://tools.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/it-tools.svg
    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Monitoring
          sites:
            - title: Dozzle
              url: https://dozzle.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/dozzle.svg
            - title: Portainer
              url: https://portainer.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/dozzle.svg