- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: monitor
          cache: 1m
          title: Misc
          sites:
            - title: Pocket-ID
              url: https://id.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pocket-id.svg
            - title: Outline
              url: https://docs.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/outline.svg
            - title: IT-Tools
              url: https://tools.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/it-tools.svg
        - type: monitor
          cache: 1m
          title: Monitoring
          sites:
            - title: Dozzle
              url: https://dozzle.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/dozzle.svg
            - title: Portainer
              url: https://portainer.docker-prd.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/portainer.svg

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news      

    - size: small
      widgets:
        - type: weather
          units: metric
          hour-format: 24
          location: Hannover, Germany
        - type: server-stats
          servers:
            - type: local
              name: srv-docker
