---
services:
  it-tools:
    image: ghcr.io/corentinth/2024.5.13-a0bc346
    container_name: it-tools
    networks:
      - proxy
    volumes:
      - it-tools-data:/app/config
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  it-tools-data: