http:
  routers:
    unraid:
      entryPoints:
        - "https"
      rule: "Host(`unraid.swarm.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: unraid
  services:
    unraid:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi"
        passHostHeader: true