services:
  traefik:
    image: traefik:v3.4.1
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy-swarm
      - socket-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - POCKET_ID_SECRET=${POCKET_ID_SECRET}
      - POCKET_ID_CLIENT_SECRET=${POCKET_ID_CLIENT_SECRET}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
      - /home/mgrsys/docker/traefik/config/certs/acme.json:/etc/traefik/acme.json
      - /mnt/shared/traefik/logs:/logs
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=http"
        - "traefik.http.routers.traefik.rule=Host(`traefik.swarm.darksaber.fyi`)"
        - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
        - "traefik.http.routers.traefik-secure.entrypoints=https"
        - "traefik.http.routers.traefik-secure.rule=Host(`traefik.swarm.darksaber.fyi`)"
        - "traefik.http.routers.traefik-secure.middlewares=pocket-id@file"
        - "traefik.http.routers.traefik-secure.tls=true"
        - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
        - "traefik.http.routers.traefik-secure.tls.domains[0].main=darksaber.fyi"
        - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.darksaber.fyi,*.swarm.darksaber.fyi"
        - "traefik.http.routers.traefik-secure.service=api@internal"
        - "traefik.http.services.traefik-secure.loadbalancer.server.port=443"


networks:
  proxy-swarm:
    external: true
  socket-proxy:
    external: true