---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Network:
    - Technitium-01:
        href: https://dns-01.darksaber.fyi
        widget:
            type: technitium
            url: https://dns-01.darksaber.fyi
            key: {{HOMEPAGE_VAR_TECHNITIUM_01_KEY}}
            range: LastDay

- Media:
    - Calender:
        name: Calendar
        widget:
            type: calendar
            integrations:
                - type: sonarr
                  service_group: Media
                  service_name: Sonarr
                  params:
                    unmonitored: false
                - type: radarr
                  service_group: Media
                  service_name: Radarr
                  params:
                    unmonitored: false


