---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Home:
    tab: First
    style: row
    columns: 4
    
  Media:
    tab: Second
    style: row
    columns: 4
  
