---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Misc:
    tab: Home
    style: row
    columns: 4
  
  Monitoring:
    tab: Home
    style: row
    columns: 4
  
  Network:
    tab: Home
    style: row
    columns: 4
    
  Media:
    tab: Media
    style: row
    columns: 2
  
