---
- name: Deploy cloudflare-ddns Service
  hosts: docker
  vars:
    service_name: cloudflare-ddns
    secret_files:
      - { template: "{{ compose_dir }}/.env.tpl", dest: "{{ compose_dir }}/.env" }

  tasks:
    - name: Clone repository
      include_tasks: ../../tasks/docker/clone-repo.yml

    - name: Prepare directories
      include_tasks: ../../tasks/docker/prepare-directories.yml
    
    - name: Copy service files
      include_tasks: ../../tasks/docker/copy-files.yml

    - name: Cleanup repository
      include_tasks: ../../tasks/docker/cleanup-repo.yml

  handlers:
    - import_tasks: ../../handlers/docker/process-secrets.yml
    - import_tasks: ../../handlers/docker/docker-service.yml