---
- name: Deploy it-tools Service
  hosts: docker
  vars:
    service_name: it-tools

  tasks:
    - name: Clone repository
      include_tasks: ../../tasks/clone-repo.yml
    
    - name: Service prerequisites
      include_tasks: ../../tasks/service-prereq.yml

    - name: Deploy service
      include_tasks: ../../tasks/deploy-service.yml
    
    - name: Cleanup repository
      include_tasks: ../../tasks/cleanup-repo.yml