---
- name: Deploy searxng Service
  hosts: docker
  vars:
    service_name: searxng
    additional_directories:
      - config
    copy_directories:
      - { src: "config", dest: "config" }

  tasks:
    - name: Clone repository
      include_tasks: ../../tasks/docker/clone-repo.yml

    - name: Prepare directories
      include_tasks: ../../tasks/docker/prepare-directories.yml
    
    - name: Copy service files
      include_tasks: ../../tasks/docker/copy-files.yml

    - name: Inject Secrets from 1Password
      shell: |
        op inject -i "{{ item.input }}" -o "{{ item.output }}" -f
      loop:
        - { input: "/home/mgrsys/docker/searxng/config/settings.yml.tpl", output: "/home/mgrsys/docker/searxng/config/settings.yml" }
      environment:
        OP_SERVICE_ACCOUNT_TOKEN: "{{ op_token }}"
      no_log: yes

    - name: Change permissions of searxng/settings.yml
      ansible.builtin.file:
        path: "/home/mgrsys/docker/searxng/config/settings.yml"
        mode: "0644"

    - name: Deploy/update and restart docker container
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        files:
          - docker-compose.yml
        state: present
        pull: policy
        recreate: always

    - name: Uncomment cap_drop in docker-compose.yml
      ansible.builtin.replace:
        path: "{{ compose_dir }}/docker-compose.yml"
        regexp: '^(\s*)#(\s*)cap_drop:'
        replace: '\1\2cap_drop:'

    - name: Uncomment - ALL in docker-compose.yml
      ansible.builtin.replace:
        path: "{{ compose_dir }}/docker-compose.yml"
        regexp: '^(\s*)#(\s*)- ALL'
        replace: '\1\2- ALL'

    - name: Cleanup repository
      include_tasks: ../../tasks/docker/cleanup-repo.yml

  handlers:
    - import_tasks: ../../handlers/docker/docker-service.yml