---
- name: Deploy Traefik Service
  hosts: docker
  vars:
    service_name: traefik-stack
    copy_directories:
      - { src: "traefik", dest: "traefik" }
    secret_files:
      - { template: "{{ compose_dir }}/.env.tpl", dest: "{{ compose_dir }}/.env" }
      - { template: "{{ compose_dir }}/cf-token.tpl", dest: "{{ compose_dir }}/cf-token" }

  tasks:
    - name: Clone repository
      include_tasks: ../../tasks/docker/clone-repo.yml

    - name: Ensure logrotate is installed
      package:
        name: logrotate
        state: present
      become: true

    - name: Prepare directories
      include_tasks: ../../tasks/docker/prepare-directories.yml
    
    - name: Copy service files
      include_tasks: ../../tasks/docker/copy-files.yml

    - name: check if acme.json exists
      stat:
        path: "{{ certs_dir }}/acme.json"
      register: acme_file
      
    - name: Create acme.json with correct permission if it does not exist
      ansible.builtin.file:
        path: "{{ certs_dir }}/acme.json"
        state: touch
        mode: "0600"
        owner: "mgrsys"
        group: "mgrsys"
      when: acme_file.stat.exists == False

    - name: Ensure logrotate configuration for Traefik
      copy:
        dest: /etc/logrotate.d/traefik
        content: |
          compress
          /var/log/traefik/logs/*.log {
            size 20M
            daily
            rotate 14
            missingok
            notifempty
            postrotate
              docker kill --signal="USR1" traefik
            endscript
          }
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Cleanup repository
      include_tasks: ../../tasks/docker/cleanup-repo.yml

  handlers:
    - import_tasks: ../../handlers/docker/process-secrets.yml
    - import_tasks: ../../handlers/docker/docker-service.yml