---
- name: Deploy Boilerplate Service
  hosts: docker
  vars:
    service_name: boilerplate
    
    # Additional directories beyond the default compose and config
    additional_directories:
      - config
      - appdata

    # Copy additional directorys if needed for config files etc.
    copy_directories:
      - { src: "config", dest: "config" }
      - { src: "appdata", dest: "appdata" }
    
    # Secret files to process with 1Password
    secret_files:
      - { template: "{{ compose_dir }}/.env.tpl", dest: "{{ compose_dir }}/.env" }
      - { template: "{{ config_dir }}/app.conf.tpl", dest: "{{ config_dir }}/app.conf" }

  tasks:
    - name: Clone repository
      include_tasks: ../../tasks/docker/clone-repo.yml

    - name: Prepare directories
      include_tasks: ../../tasks/docker/prepare-directories.yml
    
    - name: Copy service files
      include_tasks: ../../tasks/docker/copy-files.yml
      register: copy_result

    - name: Process secrets
      include_tasks: ../../tasks/docker/process-secrets.yml
      when: copy_result.changed

    - name: Deploy service
      include_tasks: ../../tasks/docker/deploy-service.yml
      when: copy_result.changed
    
    - name: Cleanup repository
      include_tasks: ../../tasks/docker/cleanup-repo.yml