---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
    volumes:
      - /mnt/user/appdata/duplicati/config:/config
      - /mnt/user/data:/source
    networks:
      - proxy
    ports:
      - 8200:8200
    restart: unless-stopped
    labels:
      # Glance
      - "glance.name=Duplicati"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/duplicati.svg"
      - "glance.url=https://duplicati.docker-prd.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=misc-srv-unraid"

networks:
  proxy:
    external: true