---
- name: Post-provisioning setup for VM
  hosts: docker
  become: true

  tasks:
    - name: Ensure system packages are up to date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisites for Docker repository
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.asc

    - name: Add Docker repository
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Allow mgrsys to run sudo without password
      copy:
        dest: /etc/sudoers.d/mgrsys
        content: "mgrsys ALL=(ALL) NOPASSWD:ALL"
        mode: 0440

    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Install 1Password CLI
      shell: |
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
        echo 'deb [signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | tee /etc/apt/sources.list.d/1password.list
        apt update && apt install -y 1password-cli

    - name: Add mgrsys to Docker group
      user:
        name: mgrsys
        groups: docker
        append: yes

    - name: Ensure NFS utilities are installed
      apt:
        name: nfs-common
        state: present

    - name: Create mount point for NFS share
      file:
        path: /mnt/data
        state: directory
        mode: '0755'      

    - name: Mount external NFS share
      mount:
        path: /mnt/data
        src: srv-unraid.local.darksaber.fyi:/mnt/user/data
        fstype: nfs
        opts: rw,noatime,_netdev,vers=4
        state: mounted

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted