services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle_agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    ports:
      - 7007:7007

networks:
  proxy:
    external: true