---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:2.1.0
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${WEBSERVICE_PASSWORD}
    volumes:
      - /opt/stacks/duplicati/config:/config
      - /mnt/data:/source
    networks:
      - proxy
    restart: unless-stopped
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.prod.darksaber.fyi`)"
      - "traefik.http.routers.duplicati.entrypoints=https"
      - "traefik.http.routers.duplicati.tls=true"
      - "traefik.http.routers.duplicati.middlewares=secured@file"
      - "traefik.docker.network=proxy"
      # Glance
      - "glance.name=Duplicati"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/duplicati.svg"
      - "glance.url=https://duplicati.prod.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=misc"

networks:
  proxy:
    external: true