---
services:
  plex:
    image: lscr.io/linuxserver/plex:1.41.7.9823-59f304c16-ls267
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM}
    volumes:
      - /mnt/user/appdata/plex/config:/config
      - /tmp/plex:/transcode
      - /mnt/user/data/media/tv:/tv
      - /mnt/user/data/media/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped