http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    gzip:
      compress: {}

    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-whitelist:
      ipAllowList:
        sourceRange:
        - 127.0.0.1/32
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"
        #ipstrategy: # enable this when cloudflare proxy in use
        #  depth: 1 # enable this when cloudflare proxy in use

    # rate limiting
    rate-limit:
      rateLimit:
        average: 100
        period: 1
        burst: 100

    pocket-id:
      plugin:
        traefik-oidc-auth:
          Secret: "{{ env `POCKET_ID_SECRET` }}"
          Provider:
            Url: "https://id.darksaber.fyi/"
            ClientId: 4a6cbb74-10e6-4644-a3f6-92e23c67c56a
            ClientSecret: ${POCKET_ID_CLIENT_SECRET}
            TokenValidation: "IdToken"
          Scopes: ["openid", "profile", "email"]
          SessionCookie:
            MaxAge: 28800

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers

    secured-external:
      chain:
        middlewares:
        - default-headers