http:
  routers:
    portainer:
      entryPoints:
        - "https"
      rule: "Host(`portainer.swarm.darksaber.fyi`)"
      middlewares:
        - secured
      tls:
        options: default
      service: portainer
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://srv-swrm-mgr.local.darksaber.fyi:9443"
        passHostHeader: true