- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: group
          widgets:
            - type: hacker-news   
            - type: rss
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://selfh.st/rss/
                  title: selfh.st   
        

    - size: full
      widgets:
        - type: docker-containers
          title: Misc
          category: misc
          sock-path: tcp://socket-proxy:2375
        - type: monitor
          cache: 1m
          title: Network
          sites:
            - title: Technitium-01
              url: https://dns-01.prod.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/technitium.svg
              same-tab: true
            - title: Technitium-02
              url: https://dns-02.prod.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/technitium.svg
              same-tab: true
            - title: Pihole-01
              url: https://pihole-01.prod.darksaber.fyi/admin/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pi-hole.svg
              same-tab: true
            - title: Pihole-02
              url: https://pihole-02.prod.darksaber.fyi/admin/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pi-hole.svg
              same-tab: true
            - title: Unifi
              url: https://unifi.ui.com/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/ubiquiti-unifi-light.svg
              same-tab: true
        - type: monitor
          cache: 1m
          title: Appliances
          sites:
            - title: Unraid
              url: https://unraid.prod.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/unraid.svg
              same-tab: true
            - title: PVE-S13-01
              url: https://pve-s13-01.local.darksaber.fyi:8006/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/proxmox.svg
              same-tab: true
            - title: PVE-S13-02
              url: https://pve-s13-02.local.darksaber.fyi:8006/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/proxmox.svg
              same-tab: true
            - title: PVE-UGREEN-03
              url: https://pve-ugreen-03.local.darksaber.fyi:8006/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/proxmox.svg
              same-tab: true
            - title: PBS
              url: https://srv-pbs.local.darksaber.fyi:8007/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/proxmox.svg
              same-tab: true
            - title: Homeassistant
              url: https://ha.prod.darksaber.fyi
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/home-assistant.svg
              same-tab: true

    - size: small
      widgets:
        - type: weather
          units: metric
          hour-format: 24h
          location: Hannover, Germany
        - type: server-stats
          servers:
            - type: local
              name: srv-docker-prod
        - type: repository
          repository: L3odalton/homelab-2.0

