---
services:
  opencloud:
    volumes:
      # the cloud importer needs to be enabled in the web.yaml
      - /home/mgrsys/docker/opencloud/config/apps.yaml:/etc/opencloud/apps.yaml
    depends_on:
      importer-init:
        condition: service_completed_successfully

  importer-init:
    image: opencloudeu/web-extensions:importer-1.0.0
    user: root
    volumes:
      - opencloud-apps:/apps
    entrypoint:
      - /bin/sh
    command: [ "-c", "cp -R /usr/share/nginx/html/importer/ /apps" ]

  companion:
    image: transloadit/companion:5.5.0
    networks:
      - proxy
    environment:
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      COMPANION_DATADIR: /tmp/companion/
      COMPANION_DOMAIN: ${COMPANION_DOMAIN}
      COMPANION_PROTOCOL: https
      COMPANION_UPLOAD_URLS: "^https://${OC_DOMAIN}/"
      COMPANION_ONEDRIVE_KEY: "${COMPANION_ONEDRIVE_KEY}"
      COMPANION_ONEDRIVE_SECRET: "${COMPANION_ONEDRIVE_SECRET}"
    volumes:
      - companion-data:/tmp/companion/
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.companion.loadbalancer.server.port=3020"
      - "traefik.http.routers.companion.rule=Host(`${COMPANION_DOMAIN}`)"
      - "traefik.http.routers.companion.entrypoints=https"
      - "traefik.http.routers.companion.tls=true"
      - "traefik.docker.network=proxy"

    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

volumes:
  companion-data: