services:
  pihole:
    container_name: pihole
    image: ghcr.io/pi-hole/pihole:2025.06.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_api_password: '${FTLCONF_webserver_api_password}'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - /opt/stacks/pihole:/etc/pihole
    cap_add:
      - SYS_NICE
    restart: unless-stopped