---
services:  
  opencloud:
    image: opencloudeu/opencloud-rolling:v1.0.0
    container_name: opencloud
    networks:
      - proxy
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      OC_ADD_RUN_SERVICES: ${START_ADDITIONAL_SERVICES}
      OC_URL: ${OC_DOMAIN}
      OC_LOG_LEVEL: "info"
      OC_LOG_COLOR: "false"
      OC_LOG_PRETTY: "false"
      PROXY_TLS: "false"
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      OC_INSECURE: "false"
      PROXY_ENABLE_BASIC_AUTH: "false"
      IDM_ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      IDM_CREATE_DEMO_USERS: false
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      COLLABORA_DOMAIN: ${COLLABORA_DOMAIN}
      ONLYOFFICE_DOMAIN: ${ONLYOFFICE_DOMAIN}
      COMPANION_DOMAIN: ${COMPANION_DOMAIN}
    volumes:
      - /home/mgrsys/docker/opencloud/config/app-registry.yaml:/etc/opencloud/app-registry.yaml
      - /home/mgrsys/docker/opencloud/config/csp.yaml:/etc/opencloud/csp.yaml
      - opencloud-config:/etc/opencloud
      - opencloud-data:/var/lib/opencloud
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.opencloud.loadbalancer.server.port=9200"
      - "traefik.http.routers.opencloud.rule=Host(`${OC_DOMAIN}`)"
      - "traefik.http.routers.opencloud.entrypoints=https"
      - "traefik.http.routers.opencloud.tls=true"
      - "traefik.http.routers.opencloud.middlewares=secured-external@file"
      - "traefik.docker.network=proxy"
    logging:
      driver: local
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  opencloud-config:
  opencloud-data: