---
x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy
    ports:
      - 8181:8080
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}
    labels:
      - "traefik.enable=true"
      - "kop.bind.ip=srv-unraid.local.darksaber.fyi"
      # Sab
      - "traefik.http.routers.sab.service=sab"
      - "traefik.http.routers.sab.rule=Host(`sab.darksaber.fyi`)"
      - "traefik.http.routers.sab.entrypoints=https"
      - "traefik.http.routers.sab.tls=true"
      - "traefik.http.routers.sab.middlewares=default-acl@docker"
      - "traefik.http.services.sab.loadbalancer.server.port=8181"  
    restart: unless-stopped
  
  sabnzbd:
    image: "11notes/sabnzbd:4.5.3-unraid"
    <<: *lockdown
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "sabnzbd.etc:/sabnzbd/etc"
      - /mnt/user/data/usenet/complete:/data/usenet/complete
      - /mnt/user/data/usenet/incomplete:/data/usenet/incomplete
    tmpfs:
      # required for read-only image
      - "/tmp:uid=99,gid=100"
    network_mode: "service:gluetun"
    restart: "unless-stopped"

networks:
  proxy:
    external: true

volumes:
  sabnzbd.etc:
