---
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1.2.0
    container_name: pocket-id
    networks:
      - proxy
    env_file: .env
    volumes:
      - pocket-id_data:/app/data
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.pocket-id.loadbalancer.server.port=1411"
      - "traefik.http.routers.pocket-id.rule=Host(`id.darksaber.fyi`)"
      - "traefik.http.routers.pocket-id.entrypoints=https"
      - "traefik.http.routers.pocket-id.tls=true"
      - "traefik.http.routers.pocket-id.middlewares=secured-external@file"
      - "traefik.docker.network=proxy"
      # Homepage
      - "homepage.group=Misc"
      - "homepage.name=Pocket-ID"
      - "homepage.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pocket-id.svg"
      - "homepage.href=https://id.darksaber.fyi"
      - "homepage.description=Simple OIDC authentication provider"
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

networks:
  proxy:
    external: true

volumes:
  pocket-id_data:
