---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.28.0
    container_name: audiobookshelf
    networks:
      - proxy
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /opt/stacks/audiobookshelf/config:/config
      - /opt/stacks/audiobookshelf/metadata:/metadata
      - /mnt/data/media/audiobooks:/audiobooks
      - /mnt/data/media/podcasts:/podcasts
      - /mnt/data/media/radioplays:/radioplays
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.abs.loadbalancer.server.port=80"
      - "traefik.http.routers.abs.rule=Host(`abs.darksaber.fyi`)"
      - "traefik.http.routers.abs.entrypoints=https"
      - "traefik.http.routers.abs.tls=true"
      - "traefik.http.routers.abs.middlewares=secured@file"
      - "traefik.docker.network=proxy"
      # Glance
      - "glance.name=Audiobookshelf"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/audiobookshelf.svg"
      - "glance.url=https://abs.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=player"
    restart: unless-stopped

networks:
  proxy:
    external: true