---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:V3.1.4
    container_name: calibre-web-automated
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /opt/stacks/calibre-web-automated/config:/config
      - ingest:/cwa-book-ingest
      - books:/calibre-library
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.cwa.loadbalancer.server.port=8083"
      - "traefik.http.routers.cwa.rule=Host(`books.prod.darksaber.fyi`)"
      - "traefik.http.routers.cwa.entrypoints=https"
      - "traefik.http.routers.cwa.tls=true"
      - "traefik.http.routers.cwa.middlewares=secured@file"
      - "traefik.docker.network=proxy"
      # Glance
      - "glance.name=Calibre"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/calibre.svg"
      - "glance.url=https://books.prod.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=player"
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  ingest:
    driver_opts:
      type: "nfs"
      o: "addr=srv-unraid.local.darksaber.fyi,nolock,soft,nfsvers=4"
      device: ":/mnt/user/data/usenet/complete/books"
  books:
    driver_opts:
      type: "nfs"
      o: "addr=srv-unraid.local.darksaber.fyi,nolock,soft,nfsvers=4"
      device: ":/mnt/user/data/media/books"