---
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:2.15.2
    container_name: tautulli
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /opt/stacks/tautulli/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.prod.darksaber.fyi`)"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.middlewares=secured@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  tautulli_config: