---
services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    networks:
      - proxy
    volumes:
      - /opt/stacks/it-tools/config:/app/config
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
      - "traefik.http.routers.it-tools.rule=Host(`tools.prod.darksaber.fyi`)"
      - "traefik.http.routers.it-tools.entrypoints=https"
      - "traefik.http.routers.it-tools.tls=true"
      - "traefik.http.routers.it-tools.middlewares=secured@file,pocket-id@file"
      - "traefik.docker.network=proxy"
      # Glance
      - "glance.name=IT-Tools"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/it-tools.svg"
      - "glance.url=https://tools.prod.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=misc"
    restart: unless-stopped

networks:
  proxy:
    external: true