---
- name: Set base service path
  set_fact:
    base_dir: "{{ base_path }}/{{ service_name }}"
    compose_dir: "{{ base_path }}/{{ service_name }}/compose"

- name: Ensure default directories exist
  file:
    path: "{{ compose_dir }}"
    state: directory
    mode: "0755"

- name: Ensure additional directories exist (if specified)
  file:
    path: "{{ base_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  loop: "{{ additional_directories | default([]) }}"
  when: additional_directories is defined

- name: Ensure docker network exists
  docker_network:
    name: "{{ docker_network }}"
    state: present

- name: Copy compose files from repo
  copy:
    src: "{{ repo_dir }}/docker/{{ service_name }}/compose/"
    dest: "{{ compose_dir }}/"
    remote_src: yes

- name: Copy additional directories
  copy:
    src: "{{ repo_dir }}/docker/{{ service_name }}/{{ item.src }}/"
    dest: "{{ base_dir }}/{{ item.dest }}/"
    remote_src: yes
  loop: "{{ copy_directories | default([]) }}"
  when: copy_directories is defined

- name: Process secret files if specified
  block:
    - name: Remove existing secret files
      file:
        path: "{{ item.dest }}"
        state: absent
      loop: "{{ secret_files }}"
      
    - name: Inject secrets from 1Password
      shell: |
        op inject -i "{{ item.template }}" -o "{{ item.dest }}"
      environment:
        OP_SERVICE_ACCOUNT_TOKEN: "{{ op_token }}"
      loop: "{{ secret_files }}"
      no_log: true
  when: secret_files is defined