services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:3.2.1
    container_name: socket-proxy
    networks:
      - proxy
    ports:
      - 2375:2375
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run

networks:
  proxy:
    external: true