---  
- name: process secrets
  shell: |
    op inject -i "{{ item.template }}" -o "{{ item.dest }}" -f
  environment:
    OP_SERVICE_ACCOUNT_TOKEN: "{{ op_token }}"
  loop: "{{ secret_files }}"
  no_log: true