global:
  checkNewVersion: true
  sendAnonymousUsage: false

metrics:
  prometheus:
    addRoutersLabels: true

entryPoints:
  http:
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

serversTransport:
  insecureSkipVerify: true

providers:
  providersThrottleDuration: 10s # This specific provider setting is best here

certificatesResolvers:
  cloudflare:
    acme:
      # caServer is optional if using production default, but harmless to keep
      caServer: https://acme-v02.api.letsencrypt.org/directory # production (default)

accessLog:
  filters:
    statusCodes:
      - "200-299"
      - "400-599"
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep