---
- name: Upgrade Ubuntu hosts
  hosts: ubuntu
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: no
      notify: reboot host

    - name: Remove unused packages and old kernels
      ansible.builtin.apt:
        autoremove: yes
        purge: yes

  handlers:
    - name: reboot host
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami