---
- name: Update all PBS VMs
  hosts: pbs
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Perform a dist-upgrade and remove old packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        purge: yes
      register: apt_upgrade_result

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server if required
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Clean up old package archives and dependencies
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
      when: not reboot_required_file.stat.exists or apt_upgrade_result.changed