- name: Install proxmox backup server upgrades
  serial: 1
  hosts: pbs
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Get upgradable packages
      ansible.builtin.shell: |
        apt list --upgradable | sed '/Listing.../d'

    - name: Show upgradable packages
      ansible.builtin.debug:
        msg: "{{ upgrades_result.stdout_lines }}"

    - name: Pause
      pause:
        prompt: Do you want to upgrade the above packages? Press enter to continue, or Ctrl+c and then "a" to abort.
      when: upgrades_result.stdout_lines|length > 0

    - name: Install apt upgrades
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true
      register: apt_upgrade_result

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Show reboot required
      ansible.builtin.debug:
        msg: Reboot required
      when: reboot_required_file.stat.exists

    - name: Reboot
      ansible.builtin.reboot:
        # Wait for LXCs and VMs to autostart. You will want to increase this if yours take longer than 30s.
        post_reboot_delay: 30
      when: reboot_required_file.stat.exists