services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:3.2.1
    container_name: traefik_socket_proxy
    networks:
      - traefik_net
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    restart: always

  traefik:
    image: traefik:v3.4.3
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    depends_on:
      socket-proxy:
        condition: service_started
    networks:
      - proxy
      - traefik_net
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - POCKET_ID_SECRET=${POCKET_ID_SECRET}
      - POCKET_ID_CLIENT_SECRET=${POCKET_ID_CLIENT_SECRET}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
      - /opt/stacks/traefik/certs/acme.json:/etc/traefik/acme.json
      - /opt/stacks/traefik/logs:/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.prod.darksaber.fyi`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.prod.darksaber.fyi`)"
      - "traefik.http.routers.traefik-secure.middlewares=pocket-id@file"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=darksaber.fyi"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.darksaber.fyi,*.prod.darksaber.fyi"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik-secure.loadbalancer.server.port=443"
    restart: always

networks:
  proxy:
    external: true
  traefik_net:
    external: false