services:
  booklore:
    image: ghcr.io/booklore-app/booklore:v0.38.2
    container_name: booklore
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/mariadb
      - DATABASE_USERNAME=mariadb
      - DATABASE_PASSWORD=${DB_PW}
      - BOOKLORE_PORT=6060
      - SWAGGER_ENABLED=false
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - booklore_appdata:/app/data
      - books:/books
      - bookdrop:/bookdrop
    networks:
      - booklore_net
      - proxy
    restart: unless-stopped
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.booklore.loadbalancer.server.port=6060"
      - "traefik.http.routers.booklore.rule=Host(`booklore.prod.darksaber.fyi`)"
      - "traefik.http.routers.booklore.entrypoints=https"
      - "traefik.http.routers.booklore.tls=true"
      - "traefik.http.routers.booklore.middlewares=secured-external@file"
      - "traefik.docker.network=proxy"
      # Glance
      - "glance.name=Booklore"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/booklore.svg"
      - "glance.url=https://booklore.prod.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=player"

  mariadb:
    image: 11notes/mariadb:11.4.5
    read_only: true
    container_name: mariadb
    environment:
      - TZ=Europe/Berlin
      - MARIADB_PASSWORD=${DB_PW}
    volumes:
      - "db_etc:/mariadb/etc"
      - "db_var:/mariadb/var"
      - "db_backup:/mariadb/backup"
      - "db_cmd:/run/cmd"
    networks:
      - booklore_net
    tmpfs:
      - "/run/mariadb:uid=1000,gid=1000"
    restart: unless-stopped

networks:
  proxy:
    external: true
  booklore_net:
    internal: true

volumes:
  db_etc:
  db_var:
  db_backup:
  db_cmd:
  booklore_appdata:
  books:
    driver: local
    driver_opts:
      type: nfs
      o: addr=srv-unraid.local.darksaber.fyi,nfsvers=4,soft,rw
      device: ":/mnt/user/data/media/books"
  bookdrop:
    driver: local
    driver_opts:
      type: nfs
      o: addr=srv-unraid.local.darksaber.fyi,nfsvers=4,soft,rw
      device: ":/mnt/user/data/usenet/complete/books"