services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.134.0
    user: 99:100
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/user/data/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - immich_net
      - proxy
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.134.0-openvino
    user: 99:100
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/user/appdata/immich/model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=Europe/Berlin
    networks:
      - immich_net
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8.1.1-bookworm
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich_net
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:17-vectorchord0.3.0-pgvectors0.3.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich_net
    volumes:
      - /mnt/user/appdata/immich/immich_postgres:/var/lib/postgresql/data
    restart: always

networks:
  proxy:
    external: true
  immich_net:
    internal: true
