---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.25.1
    container_name: audiobookshelf
    networks:
      - proxy
    ports:
      - 13378:80
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/user/appdata/audiobookshelf/config:/config
      - /mnt/user/appdata/audiobookshelf/metadata:/metadata
      - /mnt/user/data/media/audiobooks:/audiobooks
      - /mnt/user/data/media/podcasts:/podcasts
      - /mnt/user/data/media/radioplays:/radioplays
    labels:
      # Glance
      - "glance.name=Audiobookshelf"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/audiobookshelf.svg"
      - "glance.url=https://abs.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=player"
    restart: unless-stopped

networks:
  proxy:
    external: true