---
services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: it-tools
    networks:
      - proxy
    volumes:
      - it-tools-data:/app/config
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
      - "traefik.http.routers.it-tools.rule=Host(`tools.darksaber.fyi`)"
      - "traefik.http.routers.it-tools.entrypoints=https"
      - "traefik.http.routers.it-tools.tls=true"
      - "traefik.http.routers.it-tools.middlewares=secured@file,pocket-id-2@file"
      - "traefik.docker.network=proxy"
      # Homepage
      - "homepage.group=Misc"
      - "homepage.name=IT-Tools"
      - "homepage.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/it-tools.svg"
      - "homepage.href=https://tools.darksaber.fyi"
      - "homepage.description=Handy tools for developers"
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  it-tools-data: