services:
  technitium-01:
    container_name: technitium-01
    image: technitium/dns-server:13.6.0
    hostname: technitium-01
    domainname: local.darksaber.fyi
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=technitium-01.local.darksaber.fyi
      - DNS_SERVER_ADMIN_PASSWORD=${DNS_SERVER_ADMIN_PASSWORD}
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true
    volumes:
      - technitium.etc:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000

volumes:
  technitium.etc:
