---
- name: deploy/restart service
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dir }}"
    files:
      - docker-compose.yml
    state: present
    pull: policy
    recreate: always
    when: files_copied.changed == True