---
- name: Remove existing secret files
  file:
    path: "{{ item.dest }}"
    state: absent
  loop: "{{ secret_files }}"
  when: files_copied.changed == True
      
- name: Inject secrets from 1Password
  shell: |
    op inject -i "{{ item.template }}" -o "{{ item.dest }}"
  environment:
    OP_SERVICE_ACCOUNT_TOKEN: "{{ op_token }}"
  loop: "{{ secret_files }}"
  no_log: true
  when: files_copied.changed == True