services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.29.2
    networks:
      - proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.rule=Host(`portainer.docker-prd.darksaber.fyi`)"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.middlewares=secured@file"
      - "traefik.docker.network=proxy"
      # Homepage
      - "homepage.group=Monitoring"
      - "homepage.name=Portainer"
      - "homepage.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/portainer.svg"
      - "homepage.href=https://portainer.docker-prd.darksaber.fyi"

networks:
  proxy:
    external: true

volumes:
  portainer_data:
    driver: local