---
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:v2.15.2-ls190
    container_name: tautulli
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - tautulli_config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.docker-prd.darksaber.fyi`)"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.middlewares=secured@file"
      - "traefik.docker.network=proxy"
      # Glance
      - "glance.name=Tautulli"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/tautulli.svg"
      - "glance.url=https://tautulli.docker-prd.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=monitoring"
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  tautulli_config: