services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.4
    networks:
      - proxy
      - glance_net
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    restart: unless-stopped
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
      - "traefik.http.routers.glance.rule=Host(`glance.prod.darksaber.fyi`)"
      - "traefik.http.routers.glance.entrypoints=https"
      - "traefik.http.routers.glance.tls=true"
      - "traefik.http.routers.glance.middlewares=secured@file"
      - "traefik.docker.network=proxy"

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:3.2.1
    container_name: socket-proxy
    networks:
      - glance_net
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run   

networks:
  proxy:
    external: true
  glance_net:
    external: false