services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:3.0.10
    networks:
      - proxy-swarm
    ports:
      - target: 2375
        published: 2375
        protocol: tcp
        mode: host
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  proxy-swarm:
    external: true