services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.37.0.5076
    container_name: prowlarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /mnt/user/appdata/prowlarr/config:/config
    networks:
      - proxy
    ports:
      - 9696:9696
    labels:
      # Glance
      - "glance.name=Prowlarr"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/prowlarr.svg"
      - "glance.url=https://prowlarr.docker-prd.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=automation"
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.14.2939
    container_name: sonarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /mnt/user/appdata/sonarr/config:/config
      - /mnt/user/data:/data
    networks:
      - proxy
    ports:
      - 8989:8989
    labels:
      # Glance
      - "glance.name=Sonarr"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/sonarr.svg"
      - "glance.url=https://sonarr.docker-prd.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=automation"
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr:release-5.25.0.10024
    container_name: radarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /mnt/user/appdata/radarr/config:/config
      - /mnt/user/data:/data
    ports:
      - 7878:7878
    networks:
      - proxy
    labels:
      # Glance
      - "glance.name=Radarr"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/radarr.svg"
      - "glance.url=https://radarr.docker-prd.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=automation"
    restart: unless-stopped

  umlautadaptarr:
    image: pcjones/umlautadaptarr:latest
    ports:
      - 5006:5006
    container_name: umlautadaptarr
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED=true
      - SONARR__HOST=http://sonarr:8989
      - SONARR__APIKEY=${SONARR_APIKEY}
    networks:
      - proxy
    restart: unless-stopped

  wizarr:
    image: ghcr.io/wizarrrr/wizarr:2025.6.1
    user: 1000:1000
    container_name: wizarr
    networks:
      - proxy
    ports:
      - 5690:5690
    volumes:
      - /mnt/user/appdata/wizarr/data:/data/database
    labels:
      # Glance
      - "glance.name=Wizarr"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/wizarr.svg"
      - "glance.url=https://wizarr.docker-prd.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=automation"
    restart: unless-stopped
  
  huntarr:
    image: huntarr/huntarr:7.6.0
    container_name: huntarr
    environment:
      - TZ=Europe/Berlin
    networks:
      - proxy
    ports:
      - 9705:9705
    volumes:
      - /mnt/user/appdata/huntarr/config:/config
    labels:
      # Glance
      - "glance.name=Huntarr"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/huntarr.png"
      - "glance.url=https://huntarr.docker-prd.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=automation"
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr:0.8.3
    container_name: notifiarr
    hostname: notifiarr
    environment:
      - DN_API_KEY=${NOTIFIARR_API_KEY}
    volumes:
      - /mnt/user/appdata/notifiarr/config:/config
      - /etc/machine-id:/etc/machine-id
    networks:
      - proxy
    ports:
      - 5454:5454
    labels:
      # Glance
      - "glance.name=Notifiarr"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/notifiarr.png"
      - "glance.url=https://notifiarr.docker-prd.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=automation"
    restart: unless-stopped

networks:
  proxy:
    external: true