http:
  routers:
    komodo:
      entryPoints:
        - "https"
      rule: "Host(`komodo.prod.darksaber.fyi`)"
      middlewares:
        - secured-external
      tls:
        options: default
      service: komodo
  services:
    komodo:
      loadBalancer:
        servers:
          - url: "http://komodo_core:9120"
        passHostHeader: true