---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.3.0
    container_name: jellyseerr
    networks:
      - proxy
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Berlin
    volumes:
      - jellyseerr_config:/app/config
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.jellyseerr.rule=Host(`anfragen.darksaber.fyi`) || Host(`anfragen.docker-prd.darksaber.fyi`)"
      - "traefik.http.routers.jellyseerr.entrypoints=https"
      - "traefik.http.routers.jellyseerr.tls=true"
      - "traefik.http.routers.jellyseerr.middlewares=secured-external@file"
      - "traefik.docker.network=proxy"
      # Homepage
      - "homepage.tab=Medi"
      - "homepage.name=Jellyseerr"
      - "homepage.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/jellyseerr.svg"
      - "homepage.href=https://anfragen.docker-prd.darksaber.fyi"
      - "homepage.description=Media Requests"
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  jellyseerr_config: