http:
  routers:
    pve-s13-01:
      entryPoints:
        - "https"
      rule: "Host(`pve-s13-01.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: pve-s13-01
    pbs:
      entryPoints:
        - "https"
      rule: "Host(`pbs.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: pbs
    unraid:
      entryPoints:
        - "https"
      rule: "Host(`unraid.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: unraid
    dns-01:
      entryPoints:
        - "https"
      rule: "Host(`dns-01.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: dns-01
    dns-02:
      entryPoints:
        - "https"
      rule: "Host(`dns-02.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: dns-02
    homeassistant:
      entryPoints:
        - "https"
      rule: "Host(`ha.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: homeassistant
    semaphore:
        entryPoints:
          - "https"
        rule: "Host(`semaphore.darksaber.fyi`)"
        middlewares:
          - default-headers
          - https-redirectscheme
          - gzip
          - default-whitelist
        tls:
          options: default
        service: semaphore


  services:
    pve-s13-01:
      loadBalancer:
        servers:
          - url: "https://pve-s13-01.local.darksaber.fyi:8006"
        passHostHeader: true
    pbs:
      loadBalancer:
        servers:
          - url: "https://pbs-unraid.local.darksaber.fyi:8007/"
        passHostHeader: true
    unraid:
      loadBalancer:
        servers:
          - url: "http://unraid.local.darksaber.fyi"
        passHostHeader: true
    dns-01:
      loadBalancer:
        servers:
          - url: "http://technitium-01.local.darksaber.fyi:5380"
        passHostHeader: true
    dns-02:
      loadBalancer:
        servers:
          - url: "http://technitium-02.local.darksaber.fyi:5380"
        passHostHeader: true
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://homeassistant.local.darksaber.fyi:8123"
        passHostHeader: true
    semaphore:
      loadBalancer:
        servers:
          - url: "http://srv-semaphore.local.darksaber.fyi:3000"
        passHostHeader: true