http:
  routers:
    unraid:
      entryPoints:
        - "https"
      rule: "Host(`unraid.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: unraid
    dns-01:
      entryPoints:
        - "https"
      rule: "Host(`dns-01.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: dns-01
    dns-02:
      entryPoints:
        - "https"
      rule: "Host(`dns-02.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: dns-02
    homeassistant:
      entryPoints:
        - "https"
      rule: "Host(`ha.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: homeassistant
    semaphore:
        entryPoints:
          - "https"
        rule: "Host(`semaphore.docker-prd.darksaber.fyi`)"
        middlewares:
          - default-headers
          - https-redirectscheme
          - gzip
          - default-whitelist
        tls:
          options: default
        service: semaphore
    pihole-01:
        entryPoints:
          - "https"
        rule: "Host(`pihole-01.docker-prd.darksaber.fyi`)"
        middlewares:
          - default-headers
          - https-redirectscheme
          - gzip
          - default-whitelist
        tls:
          options: default
        service: pihole-01
    pihole-02:
        entryPoints:
          - "https"
        rule: "Host(`pihole-02.docker-prd.darksaber.fyi`)"
        middlewares:
          - default-headers
          - https-redirectscheme
          - gzip
          - default-whitelist
        tls:
          options: default
        service: pihole-02
    plex:
        entryPoints:
          - "https"
        rule: "Host(`plex.docker-prd.darksaber.fyi`)"
        middlewares:
          - default-headers
          - https-redirectscheme
          - gzip
        tls:
          options: default
        service: plex
    immich:
        entryPoints:
          - "https"
        rule: "Host(`immich.docker-prd.darksaber.fyi`)"
        middlewares:
          - secured-external
        tls:
          options: default
        service: immich


  services:
    unraid:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi"
        passHostHeader: true
    dns-01:
      loadBalancer:
        servers:
          - url: "http://technitium-01.local.darksaber.fyi:5380"
        passHostHeader: true
    dns-02:
      loadBalancer:
        servers:
          - url: "http://technitium-02.local.darksaber.fyi:5380"
        passHostHeader: true
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://homeassistant.local.darksaber.fyi:8123"
        passHostHeader: true
    semaphore:
      loadBalancer:
        servers:
          - url: "http://srv-semaphore.local.darksaber.fyi:3000"
        passHostHeader: true
    pihole-01:
      loadBalancer:
        servers:
          - url: "https://pihole-01.local.darksaber.fyi"
        passHostHeader: true
    pihole-02:
      loadBalancer:
        servers:
          - url: "https://pihole-02.local.darksaber.fyi"
        passHostHeader: true
    plex:
      loadBalancer:
        servers:
          - url: "https://srv-docker-gpu.local.darksaber.fyi:32400"
        passHostHeader: true
    immich:
      loadBalancer:
        servers:
          - url: "http://srv-docker-gpu.local.darksaber.fyi:2283"
        passHostHeader: true