http:
  routers:
    unraid:
      entryPoints:
        - "https"
      rule: "Host(`unraid.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: unraid
    dns-01:
      entryPoints:
        - "https"
      rule: "Host(`dns-01.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: dns-01
    dns-02:
      entryPoints:
        - "https"
      rule: "Host(`dns-02.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: dns-02
    homeassistant:
      entryPoints:
        - "https"
      rule: "Host(`ha.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: homeassistant
    semaphore:
      entryPoints:
        - "https"
      rule: "Host(`semaphore.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: semaphore
    pihole-01:
      entryPoints:
        - "https"
      rule: "Host(`pihole-01.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: pihole-01
    pihole-02:
      entryPoints:
        - "https"
      rule: "Host(`pihole-02.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: pihole-02
    plex:
      entryPoints:
        - "https"
      rule: "Host(`plex.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
      tls:
        options: default
      service: plex
    immich:
      entryPoints:
        - "https"
      rule: "Host(`immich.darksaber.fyi`)"
      middlewares:
        - secured-external
      tls:
        options: default
      service: immich
    sab:
      entryPoints:
        - "https"
      rule: "Host(`sab.docker-prd.darksaber.fyi`)"
      middlewares:
        - secured
      tls:
        options: default
      service: sab
    prowlarr:
      entryPoints:
        - "https"
      rule: "Host(`prowlarr.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-whitelist@file
        - pocket-id@file
      tls: true
      service: prowlarr
      priority: 1
    prowlarr-api:
      entryPoints:
        - "https"
      rule: "(Host(`prowlarr.docker-prd.darksaber.fyi`) && PathPrefix(`/api`))"
      middlewares:
        - default-whitelist@file
      tls: true
      service: prowlarr
      priority: 3
    sonarr:
      entryPoints:
        - "https"
      rule: "Host(`sonarr.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-whitelist@file
        - pocket-id@file
      tls: true
      service: sonarr
      priority: 1
    sonarr-api:
      entryPoints:
        - "https"
      rule: "(Host(`sonarr.docker-prd.darksaber.fyi`) && PathPrefix(`/api`))"
      middlewares:
        - default-whitelist@file
      tls: true
      service: sonarr
      priority: 3
    radarr:
      entryPoints:
        - "https"
      rule: "Host(`radarr.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-whitelist@file
        - pocket-id@file
      tls: true
      service: radarr
      priority: 1
    radarr-api:
      entryPoints:
        - "https"
      rule: "(Host(`radarr.docker-prd.darksaber.fyi`) && PathPrefix(`/api`))"
      middlewares:
        - default-whitelist@file
      tls: true
      service: radarr
      priority: 3
    wizarr:
      entryPoints:
        - "https"
      rule: "Host(`wizarr.darksaber.fyi`) || Host(`wizarr.docker-prd.darksaber.fyi`)"
      middlewares:
        - secured-external@file
      tls: true
      service: wizarr
    huntarr:
      entryPoints:
        - "https"
      rule: "Host(`huntarr.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-whitelist@file
        - pocket-id@file
      tls: true
      service: huntarr
    notifiarr:
      entryPoints:
        - "https"
      rule: "Host(`notifiarr.docker-prd.darksaber.fyi`)"
      middlewares:
        - default-whitelist@file
      tls: true
      service: notifiarr

  services:
    unraid:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi"
        passHostHeader: true
    dns-01:
      loadBalancer:
        servers:
          - url: "http://technitium-01.local.darksaber.fyi:5380"
        passHostHeader: true
    dns-02:
      loadBalancer:
        servers:
          - url: "http://technitium-02.local.darksaber.fyi:5380"
        passHostHeader: true
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://homeassistant.local.darksaber.fyi:8123"
        passHostHeader: true
    semaphore:
      loadBalancer:
        servers:
          - url: "http://srv-semaphore.local.darksaber.fyi:3000"
        passHostHeader: true
    pihole-01:
      loadBalancer:
        servers:
          - url: "https://pihole-01.local.darksaber.fyi"
        passHostHeader: true
    pihole-02:
      loadBalancer:
        servers:
          - url: "https://pihole-02.local.darksaber.fyi"
        passHostHeader: true
    plex:
      loadBalancer:
        servers:
          - url: "https://srv-unraid.local.darksaber.fyi:32400"
        passHostHeader: true
    immich:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi:2283"
        passHostHeader: true
    sab:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi:8080"
        passHostHeader: true
    prowlarr:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi:9696"
    sonarr:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi:8989"
    radarr:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi:7878"
    wizarr:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi:5690"
    huntarr:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi:9705"
    notifiarr:
      loadBalancer:
        servers:
          - url: "http://srv-unraid.local.darksaber.fyi:5454"