services:
  nginx:
    image: nginx:latest
    hostname: "{{.Node.Hostname}}-nginx" # Unique hostname for each replica
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - proxy-swarm
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.rule=Host(`nginx.swarm.darksaber.fyi`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.middlewares=secured@file"
      - "traefik.docker.network=proxy-swarm"

networks:
  proxy-swarm:
    external: true