services:
  technitium-01:
    container_name: technitium-01
    image: technitium/dns-server:13.6.0
    hostname: technitium-01
    domainname: local.darksaber.fyi
    depends_on:
      - pihole-01
      # - unbound-01
    networks:
      dns-network:
        ipv4_address: 172.21.0.254 
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=local.darksaber.fyi
      - DNS_SERVER_ADMIN_PASSWORD=${DNS_SERVER_ADMIN_PASSWORD}
      - DNS_SERVER_FORWARDERS=172.21.0.253
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true
    volumes:
      - /opt/stacks/technitium:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000

  pihole-01:
    container_name: pihole-01
    image: ghcr.io/pi-hole/pihole:2025.06.2
    hostname: pihole-01
    domainname: local.darksaber.fyi
    # depends_on:
    #   - unbound-01
    networks:
      dns-network:
        ipv4_address: 172.21.0.253
    ports:
      # - "53:53/tcp"
      # - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_api_password: '${FTLCONF_webserver_api_password}'
      # FTLCONF_dns_upstreams: '172.20.0.252#5335;'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - /opt/stacks/pihole:/etc/pihole
    cap_add:
      - SYS_NICE
    restart: unless-stopped

  # unbound-01:
  #   container_name: unbound-01
  #   image: madnuttah/unbound:1.23.0-0
  #   hostname: unbound-01
  #   domainname: local.darksaber.fyi
  #   # ports:
  #   #   - 5335:5335/tcp
  #   #   - 5335:5335/udp
  #   networks:
  #     dns-network:
  #       ipv4_address: 172.21.0.252 
  #   environment:
  #     TZ: Europe/Berlin
  #     UNBOUND_UID: 1000
  #     UNBOUND_GID: 1000
  #     HEALTHCHECK_PORT: 5335
  #     ENABLE_STATS: false
  #   volumes:
  #     - /opt/stacks/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw
  #     - /opt/stacks/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
  #     - /opt/stacks/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
  #     - /opt/stacks/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
  #   restart: unless-stopped
  #   healthcheck:
  #     test: /usr/local/unbound/sbin/healthcheck.sh
  #     interval: 60s
  #     retries: 5
  #     start_period: 15s
  #     timeout: 30s

networks:
  dns-network:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1