---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.20.0
    container_name: audiobookshelf
    networks:
      - proxy
    environment:
      - TZ=Europe/Berlin
    volumes:
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
      - /mnt/data/media/audiobooks:/audiobooks
      - /mnt/data/media/podcasts:/podcasts
      - /mnt/data/media/radioplays:/radioplays
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`abs.docker-prd.darksaber.fyi`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=https"
      - "traefik.http.routers.audiobookshelf.tls=true"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
      - "traefik.http.routers.audiobookshelf.middlewares=secured-external@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  audiobookshelf_config:
  audiobookshelf_metadata: