services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.4
    networks:
      - proxy
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    restart: unless-stopped
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
      - "traefik.http.routers.glance.rule=Host(`glance.darksaber.fyi`)"
      - "traefik.http.routers.glance.entrypoints=https"
      - "traefik.http.routers.glance.tls=true"
      - "traefik.http.routers.glance.middlewares=default-acl@docker"
      - "traefik.docker.network=proxy" 

networks:
  proxy:
    external: true