---
services:
  plex:
    image: lscr.io/linuxserver/plex:1.42.1
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM}
    volumes:
      - /opt/stacks/plex/config:/config
      - /tmp/plex:/transcode
      - tv:/tv
      - movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      # Glance
      - "glance.name=Plex"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/plex.svg"
      - "glance.url=https://plex.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=player"

volumes:
  tv:
    driver_opts:
      type: "nfs"
      o: "addr=srv-unraid.local.darksaber.fyi,nolock,soft,nfsvers=4"
      device: ":/mnt/user/data/media/tv"
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=srv-unraid.local.darksaber.fyi,nolock,soft,nfsvers=4"
      device: ":/mnt/user/data/media/movies"