---
services:
  plex:
    image: lscr.io/linuxserver/plex:1.41.9
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM}
    volumes:
      - /opt/stacks/plex/config:/config
      - /tmp/plex:/transcode
      - /mnt/data/media/tv:/tv
      - /mnt/data/media/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      # Glance
      - "glance.name=Plex"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/plex.svg"
      - "glance.url=https://plex.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=player"