---
services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}
    labels:
      - "traefik.enable=true"
      # Sab
      - "traefik.http.routers.sab.service=sab"
      - "traefik.http.routers.sab.rule=Host(`sab.prod.darksaber.fyi`)"
      - "traefik.http.routers.sab.entrypoints=https"
      - "traefik.http.routers.sab.tls=true"
      - "traefik.http.routers.sab.middlewares=secured@file"
      - "traefik.http.services.sab.loadbalancer.server.port=8080"  
    restart: unless-stopped

  sabnzbd:
    image: ghcr.io/hotio/sabnzbd:release-4.5.3
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - /opt/stacks/sabnzbd/config:/config
      - /mnt/data/usenet/complete:/data/usenet/complete
      - /mnt/data/usenet/incomplete:/data/usenet/incomplete
    network_mode: "service:gluetun"
    restart: unless-stopped
    labels:
    # Glance
      - "glance.name=Sabnzbd"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/sabnzbd.svg"
      - "glance.url=https://sab.prod.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=automation"

networks:
  proxy:
    external: true
