---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.6.0
    container_name: jellyseerr
    networks:
      - proxy
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Berlin
    volumes:
      - /opt/stacks/jellyseerr/config:/app/config
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.jellyseerr.rule=Host(`anfragen.darksaber.fyi`)"
      - "traefik.http.routers.jellyseerr.entrypoints=https"
      - "traefik.http.routers.jellyseerr.tls=true"
      - "traefik.http.routers.jellyseerr.middlewares=secured-external@file"
      - "traefik.docker.network=proxy"
      # Glance
      - "glance.name=Jellyseerr"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/jellyseerr.svg"
      - "glance.url=https://anfragen.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=automation"
    restart: unless-stopped

networks:
  proxy:
    external: true