---
services:
  wallos:
    image: ghcr.io/ellite/wallos:3.3.0
    container_name: wallos
    networks:
      - proxy
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Berlin
    volumes:
      - /opt/stacks/wallos/db:/var/www/html/db
      - /opt/stacks/wallos/logos:/var/www/html/images/uploads/logos
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.wallos.loadbalancer.server.port=80"
      - "traefik.http.routers.wallos.rule=Host(`wallos.prod.darksaber.fyi`)"
      - "traefik.http.routers.wallos.entrypoints=https"
      - "traefik.http.routers.wallos.tls=true"
      - "traefik.http.routers.wallos.middlewares=secured@file"
      - "traefik.docker.network=proxy"
      # Glance
      - "glance.name=wallos"
      - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/svg/wallos.svg"
      - "glance.url=https://wallos.prod.darksaber.fyi"
      - "glance.same-tab=true"
      - "glance.category=misc"
    restart: unless-stopped

networks:
  proxy:
    external: true