name: Run Ansible Playbooks on File Change

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'

jobs:
  run-playbooks:
    runs-on: self-hosted
    environment: ansible

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: dorny/paths-filter@v3
      with:
        filters: |
          dozzle:
            - 'docker/dozzle/**'

    - name: Run Ansible Playbook for Dozzle
      if: steps.changed-files.outputs.dozzle == 'true'
      uses: dawidd6/action-ansible-playbook@v3
      with:
        playbook: playbooks/stacks/dozzle.yml
        directory: ansible
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        options: |
          --extra-vars "op_token=${{ secrets.OP_TOKEN }}"
          --inventory ${{ github.workspace }}/ansible/inventory/inventory.ini