name: Run Ansible Playbooks on File Change

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'

jobs:
  detect-changes:
    runs-on: self-hosted
    outputs:
      changed-services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate filters
        id: generate-filters
        run: |
          SERVICES=$(cat << 'EOF'
          dozzle
          traefik-stack
          it-tools
          portainer
          jellyseerr
          pocket-id
          glance
          cloudflare-ddns
          calibre-web-automated
          searxng
          plex-auto-languages
          tautulli
          EOF
          )
          FILTERS=""
          for service in $SERVICES; do
            FILTERS="${FILTERS}${service}:\n  - 'docker/${service}/**'\n"
          done
          echo "filters<<EOF" >> $GITHUB_OUTPUT
          echo -e "$FILTERS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Filter changed services
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: ${{ steps.generate-filters.outputs.filters }}
          list-files: json

  deploy-services:
    needs: detect-changes
    runs-on: self-hosted
    environment: ansible
    if: ${{ needs.detect-changes.outputs.changed-services != '[]' }}
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.changed-services) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbooks/stacks/${{ matrix.service }}.yml
          directory: ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --extra-vars "op_token=${{ secrets.OP_TOKEN }}"
            --inventory ${{ github.workspace }}/ansible/inventory/inventory.ini