name: "Terraform Deployment"

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: "Terraform"
    runs-on: self-hosted
    environment: terraform
    
    defaults:
      run:
        working-directory: ./terraform
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.12.0"

      - name: Terraform Init
        run: terraform init
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_USER: ${{ secrets.PM_USER }}
          PM_PASS: ${{ secrets.PM_PASS }}
        
      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Validate
        run: terraform validate
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_USER: ${{ secrets.PM_USER }}
          PM_PASS: ${{ secrets.PM_PASS }}

      - name: Terraform Plan
        run: terraform plan
        if: github.event_name == 'pull_request'
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_USER: ${{ secrets.PM_USER }}
          PM_PASS: ${{ secrets.PM_PASS }}
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_USER: ${{ secrets.PM_USER }}
          PM_PASS: ${{ secrets.PM_PASS }}