name: "Terraform Apply"

on:
  pull_request:
    types:
      - closed
    paths:
      - 'terraform/**'

jobs:
  apply:
    name: "Terraform Apply"
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    environment: terraform
    
    defaults:
      run:
        working-directory: ./terraform
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip curl nodejs

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.0"

      - name: Terraform Init
        run: terraform init
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_USER: ${{ secrets.PM_USER }}
          PM_PASS: ${{ secrets.PM_PASS }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_USER: ${{ secrets.PM_USER }}
          PM_PASS: ${{ secrets.PM_PASS }}