name: "Terraform Plan"

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    runs-on: self-hosted
    outputs:
      tf_dirs: ${{ steps.changes.outputs.dirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Terraform directories
        id: changes
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | \
            grep "\.tf$" | \
            xargs -I {} dirname {} | \
            sort -u | \
            jq -R -s -c 'split("\n")[:-1]')
          echo "dirs=$CHANGED_DIRS" >> $GITHUB_OUTPUT
          echo "Found changed directories: $CHANGED_DIRS"

  plan:
    needs: detect-changes
    if: fromJson(needs.detect-changes.outputs.tf_dirs)[0] != null
    runs-on: self-hosted
    environment: terraform
    
    defaults:
      run:
        working-directory: ${{ matrix.tf_dir }}
        
    strategy:
      matrix:
        tf_dir: ${{ fromJson(needs.detect-changes.outputs.tf_dirs) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip curl nodejs

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.0"

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_pass: ${{ secrets.PM_PASS }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color 2>&1 | tee plan.txt
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_pass: ${{ secrets.PM_PASS }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Terraform Plan Changes - ${{ matrix.tf_dir }}'
          body: |
            ## Terraform Plan Results for ${{ matrix.tf_dir }}
            ```hcl
            $(cat plan.txt)
            ```
          branch: terraform-changes-${{ matrix.tf_dir }}
          base: main
          labels: terraform