x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  plex:
    image: "11notes/plex:1.42.1"
    <<: *lockdown
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "plex.etc:/plex/etc"
      - "/mnt/user/data/media/tv:/tv"
      - "/mnt/user/data/media/movies:/movies"
    tmpfs:
      # /plex/tmp is required in read-only mode (can be used for transcode too)
      - "/plex/tmp:size=8G,uid=1000,gid=100"
    ports:
      - "32400:32400/tcp"
    networks:
      proxy:
    restart: "unless-stopped"
    labels:
      # Traefik
      - "traefik.enable=true"
      - "kop.bind.ip=srv-unraid.local.darksaber.fyi"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.rule=Host(`plex.darksaber.fyi`)"
      - "traefik.http.routers.plex.entrypoints=https"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.docker.network=proxy"

volumes:
  plex.etc:

networks:
  proxy:
    external: true